[project]
name = 'clarity'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.commission-trait]
path = 'contracts/commission-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidium-early-access-nft]
path = 'contracts/liquidium-early-access-nft.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidium-megapont-ape-club-vault-v1-1-1]
path = 'contracts/liquidium-megapont-ape-club-vault-v1-1-1.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidium-megapont-ape-club-vault-v1-1-2]
path = 'contracts/liquidium-megapont-ape-club-vault-v1-1-2.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidium-megapont-ape-club-vault-v1-1-3]
path = 'contracts/liquidium-megapont-ape-club-vault-v1-1-3.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidium-megapont-ape-club-vault-v1-1-4]
path = 'contracts/liquidium-megapont-ape-club-vault-v1-1-4.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidium-megapont-p2pool-loans-v1-0]
path = 'contracts/liquidium-megapont-p2pool-loans-v1-0.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidium-megapont-testnet-faucet]
path = 'contracts/liquidium-megapont-testnet-faucet.clar'
clarity_version = 1
epoch = 2.0

[contracts.liquidium-peer-to-peer-loans-v1-0-0]
path = 'contracts/liquidium-peer-to-peer-loans-v1-0-0.clar'
clarity_version = 1
epoch = 2.0

[contracts.megapont-ape-club-nft]
path = 'contracts/megapont-ape-club-nft.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip009-nft-trait]
path = 'contracts/sip009-nft-trait.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
